version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 cp ./build s3://www.tncalculator.io/ --recursive
      - aws cloudfront create-invalidation --distribution-id E1D8LIQW9NZNJX --paths "/*"
